apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  source:
    repoURL: https://github.com/rcdelacruz/openshift-testbed-apps
    targetRevision: HEAD
    path: letsencrypt
  destination:
    server: https://kubernetes.default.svc
    namespace: acme
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  #ignoreDifferences:
  #- group: v1
  #  kind: ConfigMap
  #  jsonPointers:
  #  - /data/
  #- group: route.openshift.io
  #  kind: Route
  #  jsonPointers:
  #  - /status
